#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""v9 manuscript rebuild from v08 (unified meta + joint composition + audit + wording fixes)."""
src=r"C:\Users\fengq\Desktop\EGFR\EGFR_Atlas_投稿包_v8\01_稿件正文\Manuscript_draft_v08.md"
dst=r"C:\Users\fengq\Desktop\EGFR\EGFR的v9\01_稿件正文\Manuscript_draft_v09.md"
s=open(src,encoding="utf-8").read()
R=[]
def rep(a,b): R.append((a,b))
# 0 version header note (after data freeze line)
rep("External validation cohorts GSE39582 (CRC), GSE21501 (PDAC) and ACRG/GSE62254 (gastric) added September 2026.",
    "External validation cohorts GSE39582 (CRC), GSE21501 (PDAC) and ACRG/GSE62254 (gastric) added September 2026. v9: unified-scale meta-analysis and joint composition models (September 2026).")
# 1 title
rep("a composition-adjudicated transcriptional atlas spanning six cancers and four chronic diseases",
    "a composition-aware transcriptional atlas spanning six cancers and four chronic diseases")
# 2 abstract methods
rep("Standardized effects were pooled by within-context random-effects meta-analysis. Cellular composition was estimated by xCell (EPIC cross-check) and module effects re-tested after expression-derived composition adjustment.",
    "Standardized effects were pooled by within-context random-effects meta-analysis on a unified two-group effect scale (matched-pair cohorts converted using the estimated within-pair correlation). Cellular composition was estimated by xCell (EPIC cross-check), and module effects were re-tested in joint models adjusting for composition simultaneously with disease status, with two-step xCell residualization retained only as a sensitivity.")
# 3 abstract results paragraph
rep("Fifty-five of 170 module-context states were per-cohort robust, but conservative REML/Hartung-Knapp pooling retained only 4 pooled-significant states (vs 73 at k \u2265 2 under the anti-conservative DerSimonian-Laird estimator). After xCell adjustment only 19 states remained composition-robust (CRC 10, STAD 8, ESCC 1), and all PAAD bulk effects were strongly attenuated, indicating composition-coupling rather than tumour-cell-intrinsic signal.",
    "Fifty-five of 170 module-context states were per-cohort robust. On the unified effect scale, conservative REML/Hartung-Knapp pooling retained 11 pooled states (31 under DerSimonian-Laird). In joint models that adjusted for composition simultaneously with disease status, six states remained composition-robust (CRC WNT/\u03b2-catenin, EPH, FGFR loss, IGF/INSR loss and VEGF/PDGF upregulation; IBD JAK-STAT), and all PAAD bulk effects were strongly attenuated, indicating composition-coupling rather than tumour-cell-intrinsic signal.")
# 4 abstract external sentence append CI note-free, ok as-is
# 5 methods 2.1 prospective wording
rep("External validation was prospective in three cancers:", "External validation was retrospective and independent in three cancers:")
# 6 methods 2.3 unified scale
rep("standardized effects were computed as paired mean-change/SD or Hedges' g. A direction-consistency rule defined robust states as \u2265 2/3 cohorts sharing the majority sign with \u2265 2 cohorts FDR<0.05 (2/2 for k=2). Cohort-level standardized effects were additionally pooled by within-context DerSimonian-Laird random-effects meta-analysis [20]; SMD variances were approximated as (n1+n0)/(n1\u00b7n0) + g\u00b2/2(n1+n0) (unpaired) or 1/np + d\u00b2/2np (paired, within-pair correlation 0.5), with heterogeneity reported as I\u00b2 and \u03c4\u00b2, and per-disease BH-FDR on pooled p-values. Single-cohort (k=1) estimates were reported but not treated as meta evidence. The primary pooled estimates used DerSimonian-Laird; a conservative sensitivity re-estimated the between-study variance by REML and tested pooled effects with the Hartung-Knapp adjustment (t distribution with k-1 degrees of freedom), which is recommended when the number of cohorts per context is small.",
    "standardized effects were expressed on a common two-group scale: Hedges' g (with small-sample correction) for unpaired cohorts, and for the twelve matched cohorts the paired standardized difference (d_z) was converted to the two-group scale as g \u2248 d_z\u00b7\u221a(2(1\u2212r)), where r is the within-pair correlation estimated empirically from the matched module scores (fixed r = 0.5 and 0.7 sensitivity runs returned identical pooled-significant sets; the variance of the converted estimate was 2(1\u2212r)/n_p + g\u00b2/(2(n_p\u22122))). A direction-consistency rule defined robust states as \u2265 2/3 cohorts sharing the majority sign with \u2265 2 cohorts FDR<0.05 (2/2 for k=2). Cohort-level effects were pooled by within-context random-effects meta-analysis [20]; unpaired variances were (n1+n0)/(n1\u00b7n0) + g\u00b2/(2(n1+n0)). Heterogeneity is reported as I\u00b2 and \u03c4\u00b2 and per-disease BH-FDR was applied to pooled p-values. Single-cohort (k=1) estimates were reported but not treated as meta evidence. The primary pooled estimates used DerSimonian-Laird; a conservative sensitivity re-estimated between-study variance by REML and tested pooled effects with the Hartung-Knapp adjustment (t with k\u22121 degrees of freedom).")
# 7 methods 2.4 joint composition
rep("Tissue composition was estimated by xCell v1.1.0 [19] (64 immune/stromal cell types plus ImmuneScore) on each cohort expression matrix; four compartment scores were used as covariates \u2014 Epithelial cells, Fibroblasts, Endothelial cells and ImmuneScore. Module scores were regressed on these covariates and residuals re-tested; composition-robust states were defined as \u2265 2 adjusted cohorts FDR<0.05 with stable majority direction. A marker-proxy sensitivity version (epithelial/immune/stromal/endothelial marker means) was compared by Spearman correlation across the 170 adjusted medians (\u03c1 = 0.81) and by overlap (12 of 14 marker-proxy robust states). Concordance with a second, independent deconvolution (EPIC) was assessed across all 27 cohorts (sample-level Spearman vs xCell: endothelial \u03c1 = 0.56, immune 0.44, fibroblast/CAF 0.28, epithelial/cancer 0.09). Residualization is interpreted as evidence of composition-coupling, not as proof of cell-intrinsic absence, because tissue architecture itself can be part of disease biology (Discussion).",
    "Tissue composition was estimated by xCell v1.1.0 [19] (64 immune/stromal cell types plus ImmuneScore); xCell outputs are expression-derived enrichment scores and are not measured cell proportions. Four compartment scores were used (Epithelial cells, Fibroblasts, Endothelial cells, ImmuneScore). The primary composition layer re-tested module effects in joint linear models that adjust for composition simultaneously with disease status (module score ~ disease status + the four compartment scores, plus a matched-patient factor in the twelve paired cohorts), deriving per-cohort FDR and standardized adjusted differences (coefficient divided by residual SD) from the same model. Two-step xCell residualization (regression residuals re-tested against disease) was retained only as a sensitivity because it can over- or under-correct when disease and composition are correlated; composition-robust (joint) states were defined as \u2265 2 cohorts with FDR<0.05 in the joint model and a stable majority direction. A marker-proxy sensitivity version (epithelial/immune/stromal/endothelial marker means) was compared by Spearman correlation across the 170 adjusted medians (\u03c1 = 0.81) and by overlap (12 of 14 marker-proxy robust states). Concordance with a second, independent deconvolution (EPIC) was assessed across all 27 cohorts (sample-level Spearman vs xCell: endothelial \u03c1 = 0.56, immune 0.44, fibroblast/CAF 0.28, epithelial/cancer 0.09); this low-to-moderate agreement is reported as a limitation rather than as cross-tool validation. Composition adjustment is interpreted as evidence of composition-coupling, not as proof of cell-intrinsic absence, because tissue architecture itself can be part of disease biology (Discussion).")
# 8 methods 2.9 purity pointer & methods + subtype n
rep("### 2.9 PAAD molecular subtype\nTCGA-PAAD samples were classified into basal-like versus classical",
    "### 2.9 PAAD molecular subtype and purity sensitivity\nTCGA-PAAD samples (179 with RNA-seq) were classified into basal-like versus classical")
rep("Per-sample z-scores were averaged over each program's genes and the higher score\nassigned the subtype. Module-OS Cox models were re-fit within subtype strata and with subtype interactions.",
    "Per-sample z-scores were averaged over each program's genes and the higher score assigned the subtype; 178 of 179 classified samples had survival data. Module-OS Cox models were re-fit within subtype strata and with subtype interactions. A marker-based purity sensitivity used an expression-derived immune/stromal content score as a purity proxy (proxy = \u2212(immune + stromal z-scores)); this proxy is approximate and is not a measured purity estimate.")
# 9 methods 2.10 anchors ok
# 10 results 3.1 unified meta numbers
rep("The per-cohort rule is the pre-specified primary readout. Random-effects pooling was treated as a sensitivity layer: the DerSimonian-Laird estimator identified 75 pooled-significant states (73 at k \u2265 2), but this estimator is anti-conservative when the number of cohorts per context is small (k = 2-3 here), and re-estimation of the between-study variance by REML with the Hartung-Knapp adjustment retained only 4 pooled-significant states (PAAD HGF/MET +1.20, RAS-MAPK +0.84, ERBB ligands +0.39; COPD SRC/FAK \u22120.28). NAFLD remained null at every level, within the power of the available cohorts. The largest pooled effects were CRC WNT/\u03b2-catenin (+2.59; I\u00b2=0%), CRC EPH (+1.96; I\u00b2=0%), IBD JAK-STAT (+1.77), IBD HGF-MET (+1.52), LUAD TIE (\u22121.63), LUAD FGFR (\u22121.55), PAAD HGF/MET (+1.20; I\u00b2=0%) and STAD EPH (+1.25; I\u00b2=82%).",
    "The per-cohort rule is the pre-specified primary readout. Random-effects pooling was a confirmatory layer on a unified effect scale: the DerSimonian-Laird estimator identified 31 pooled-significant states at k \u2265 2, and the conservative REML estimate with the Hartung-Knapp adjustment retained 11 (CRC WNT/\u03b2-catenin +2.58, CRC EPH +1.87, IBD JAK-STAT +1.78, IBD HGF/MET +1.52, IBD VEGF/PDGF +1.30, IBD TIE +1.14, IBD SRC/FAK +0.45, CRC ERBB ligands \u22120.37, IBD ERBB receptors \u22121.28, CRC PDGFR-KIT \u22121.07, COPD SRC/FAK \u22120.28). No PAAD state survived on the unified scale. NAFLD remained null at every level, within the power of the available cohorts. The largest pooled effects were CRC WNT/\u03b2-catenin (+2.58; I\u00b2=0%), CRC EPH (+1.87; I\u00b2=0%), IBD JAK-STAT (+1.78) and IBD HGF/MET (+1.52).")
# 11 results 3.2 label & numbers
rep("**Multi-axis activation (STAD, PAAD).** STAD lesions concordantly upregulated EPH, JAK-STAT, RAS-MAPK and HGF-MET (pooled SMD up to +1.25; eight composition-robust states); PAAD showed the broadest bulk upregulation (ten per-cohort-robust modules; pooled HGF/MET +1.20) that composition adjustment attenuated entirely (Results 3.4).",
    "**Diffuse upregulation (STAD, PAAD).** STAD lesions concordantly upregulated EPH, JAK-STAT, RAS-MAPK and HGF-MET (ten per-cohort-robust states), although none of these pooled effects survived on the unified scale or in joint composition models; PAAD showed the broadest bulk upregulation (ten per-cohort-robust modules) that joint composition adjustment attenuated entirely (Results 3.4).")
rep("**ESCC** combined SRC/FAK, VEGF/PDGF and IGF upregulation with TAM/AXL downregulation (four per-cohort-robust; SRC/FAK composition-robust).",
    "**ESCC** combined SRC/FAK, VEGF/PDGF and IGF upregulation with TAM/AXL downregulation (four per-cohort-robust); no ESCC state survived joint composition adjustment.")
# 12 results 3.3 IBD numbers
rep("IBD was the sole benign context with strong, reproducible transcriptional upregulation: pooled JAK-STAT +1.77, HGF-MET +1.52, PDGFR-KIT +1.34, VEGF/PDGF +1.30, Ang/Tie2 +1.14 and TGF\u03b2 +1.05, with ERBB-receptor downregulation (\u22121.28). Single-cell data localized JAK-STAT to both colonic epithelium and myeloid cells (Results 3.5). As for PAAD, bulk IBD upregulation was partly composition-associated: xCell residualization attenuated most IBD states, an expected consequence of adjusting for the epithelial remodelling that accompanies inflammation, and therefore does not by itself argue against epithelial-intrinsic signal (Discussion 4.4).",
    "IBD was the sole benign context with strong, reproducible transcriptional upregulation (unified-scale pooled JAK-STAT +1.78, HGF/MET +1.52, VEGF/PDGF +1.30, TIE +1.14, SRC/FAK +0.45; ERBB-receptor downregulation \u22121.28). JAK-STAT was the only IBD state that survived joint composition adjustment (3/3 cohorts FDR<0.05). Single-cell data localized JAK-STAT to both colonic epithelium and myeloid cells (Results 3.5). As for PAAD, most bulk IBD upregulation was composition-associated; the epithelial remodelling that accompanies inflammation is itself part of the disease, so composition adjustment does not by itself argue against epithelial-intrinsic signal (Discussion 4.4).")
# 13 results 3.4 joint composition rewrite
rep("After xCell-based composition adjustment, 19 states were composition-robust (CRC 10, STAD 8, ESCC 1), versus 14 by the marker-proxy sensitivity version (12 overlap; the two methods correlated \u03c1 = 0.81 across the 170 adjusted medians). Notable changes: (i) all PAAD effects were attenuated to non-significance by xCell adjustment, indicating that PAAD bulk module differences are strongly composition-associated; (ii) CRC gained ERBB ligands (down), JAK-STAT (up) and TAM/AXL (up); STAD gained ERBB receptors (down), PI3K-AKT and WNT; ESCC SRC/FAK became robust after adjustment; (iii) CRC and PAAD PDGFR-KIT lost robustness relative to the marker-proxy version. The strongest xCell-robust states were CRC WNT/\u03b2-catenin (+1.29), STAD EPH (+1.27), CRC EPH (+0.93), STAD RAS-MAPK/JAK-STAT (+0.85) and ESCC SRC/FAK (+0.86).",
    "In joint models that adjust for composition simultaneously with disease status, six states were composition-robust (CRC WNT/\u03b2-catenin, EPH, FGFR loss, IGF/INSR loss and VEGF/PDGF upregulation; IBD JAK-STAT). Two-step xCell residualization - retained as a sensitivity - classified 19 states as robust (CRC 10, STAD 8, ESCC 1), with only five states overlapping the joint set; the discrepancy indicates that residualization and joint adjustment answer different questions, and the joint models are the more conservative and are reported as primary. All PAAD effects were attenuated to non-significance in the joint models, indicating that PAAD bulk module differences are strongly composition-associated. The strongest joint-robust states were CRC WNT/\u03b2-catenin (median adjusted difference +2.47), CRC EPH (+1.36), CRC VEGF/PDGF (+1.47), CRC FGFR loss (\u22121.47) and IBD JAK-STAT (+1.03).")
# 14 results 3.6 external audit counts
rep("The adverse CRC VEGF/PDGF signal replicated in GSE39582 (HR 1.21, p=0.0069; HR 1.20, p=0.0087 after age adjustment) against the TCGA direction (HR 1.30),",
    "The adverse CRC VEGF/PDGF signal replicated in GSE39582 (n=573 after excluding samples without outcome annotation; 190 events; HR 1.21, 95% CI 1.05-1.40, p=0.0069; HR 1.20, 95% CI 1.05-1.38 after age adjustment) against the TCGA direction (HR 1.30),")
# 15 results 3.7 negative-control rename & ESCC phrasing
rep("### 3.7 Driver stratification as a negative control [Table S4]",
    "### 3.7 Driver-stratified effect-modification screen [Table S4]")
rep("None of the 108 module \u00d7 driver interaction tests survived BH-FDR, indicating that no statistically supported heterogeneity of module-OS associations across KRAS/EGFR/TP53/amplification backgrounds was detected; however, interaction analyses were underpowered (several strata had \u2264 8 events).",
    "None of the 108 module \u00d7 driver interaction tests survived BH-FDR, indicating that no statistically supported effect modification of module-OS associations across KRAS/EGFR/TP53/amplification backgrounds was detected; interaction analyses were, however, underpowered (several strata had \u2264 8 events), so this screen does not prove stability across driver backgrounds.")
rep("The ESCC EGFR dissociation is partly resolved by stratification: the protective EGFR-expression effect (HR 0.56) was carried by non-amplified patients (HR 0.48, p=0.001), while the EGFR-amplified subgroup (n=14, three events) was not estimable \u2014 no claim about amplified patients can be made from this dataset.",
    "The ESCC EGFR dissociation is partly resolved by stratification: the protective EGFR-expression effect (HR 0.56) was confined to the non-amplified patients in whom it could be estimated (HR 0.48, p=0.001); the EGFR-amplified subgroup (n=14, three events) was not estimable, so no claim about amplified patients is made from this dataset.")
# 16 results 3.8 178/179 & purity wording & pointer
rep("In TCGA-PAAD (n=178 with survival), the factor-loading classifier assigned 81 basal-like and 98 classical tumours (45% basal).",
    "In TCGA-PAAD, 179 samples were classified by the factor-loading rule (81 basal-like, 98 classical; 45% basal), of which 178 had survival data.")
rep("Tumour-purity adjustment was performed with a marker-based immune/stromal content score (purity proxy = \u2212(immune + stromal z-scores); Methods 2.10).",
    "Tumour-purity adjustment used a marker-based immune/stromal content score as an approximate purity proxy (Methods 2.9).")
rep("Together, the subtype and purity analyses show that the TCGA-single-source PAAD module-OS signals are not explained by molecular subtype or by tumour purity; because they were also not reproduced externally (Results 3.6), they remain TCGA-specific observations pending cohort-level replication.",
    "Together, the subtype and marker-based purity analyses show that the TCGA-single-source PAAD module-OS signals were not materially attenuated by the subtype classification or by the expression-derived purity proxy used here; given this approximate proxy and the lack of external replication (Results 3.6), the signals remain TCGA-specific observations pending cohort-level replication.")
# 17 results 3.9 anchors compress note & EPIC low concordance wording
rep("An independent deconvolution (EPIC) applied to all 27 cohorts agreed moderately with xCell for endothelial (\u03c1 = 0.56) and immune (\u03c1 = 0.44) fractions, but less for fibroblast/CAF (\u03c1 = 0.28) and epithelial/cancer (\u03c1 = 0.09) fractions. These layers are descriptive and hypothesis-generating only (Methods 2.10); the module-to-drug-class map is provided in Supplementary Table S2.",
    "An independent deconvolution (EPIC) applied to all 27 cohorts agreed only moderately with xCell (endothelial \u03c1 = 0.56, immune 0.44, fibroblast/CAF 0.28, epithelial/cancer 0.09), underscoring that single-tool deconvolution should be interpreted cautiously (Discussion 4.8). These layers are descriptive and hypothesis-generating only (Methods 2.10); the module-to-drug-class map is provided in Supplementary Table S2.")
# 18 Discussion 4.1 & 4.3 numbers
rep("The disciplined outcome is that a small minority of the bulk signals survive: 55 of 170 states were per-cohort robust, 19 remained composition-robust after xCell adjustment, and only a subset of those could be localized to specific cellular compartments.",
    "The disciplined outcome is that a small minority of the bulk signals survive: 55 of 170 states were per-cohort robust, six remained composition-robust in joint composition models, and only a subset of those could be localized to specific cellular compartments.")
rep("### 4.3 Surviving composition-robust signals and their cellular sources\nThe composition-robust signals were CRC WNT/EPH (malignant-cell-localized), STAD multi-axis (EPH/JAK-STAT/RAS-MAPK/HGF-MET), and ESCC SRC/FAK. Single-cell data further localized CRC WNT/EPH to malignant cells and IBD JAK-STAT to colonic epithelium and myeloid cells.",
    "### 4.3 Surviving composition-robust signals and their cellular sources\nThe joint-model-robust signals were CRC WNT/\u03b2-catenin, EPH, FGFR loss, IGF/INSR loss and VEGF/PDGF upregulation, and IBD JAK-STAT. Single-cell data localized CRC WNT/EPH and CRC VEGF/PDGF to malignant cells and IBD JAK-STAT to colonic epithelium and myeloid cells.")
# 19 Discussion 4.4 wording & numbers
rep("The adverse-OS signal of module expression in bulk TCGA RNA was not reproduced in an independent PDAC cohort (GSE21501), was not subtype-driven in basal/classical stratification, and \u2014 in a marker-based purity sensitivity \u2014 was not explained by tumour purity; these signals therefore remain TCGA-specific observations pending cohort-level replication before any prognostic claim.",
    "The adverse-OS signal of module expression in bulk TCGA RNA was not reproduced in an independent PDAC cohort (GSE21501), was not subtype-driven in basal/classical stratification, and was not attenuated in a marker-based purity sensitivity; given the approximate purity proxy and absent external replication, these signals remain TCGA-specific observations pending cohort-level replication before any prognostic claim.")
# 20 Discussion 4.6 carried entirely fix
rep("In ESCC, EGFR high-level amplification (14.6%, the highest of the six cancers) coexists with a protective single-gene EGFR expression effect (HR 0.56) that is carried entirely by non-amplified patients (HR 0.48, p=0.001), while the amplified subgroup (n=14, three events) is not estimable.",
    "In ESCC, EGFR high-level amplification (14.6%, the highest of the six cancers) coexists with a protective single-gene EGFR expression effect (HR 0.56) that is confined to the non-amplified patients in whom it could be estimated (HR 0.48, p=0.001); the amplified subgroup (n=14, three events) is not estimable.")
# 21 Discussion 4.7 heading + wording
rep("### 4.7 Driver stratification as an underpowered negative control",
    "### 4.7 Driver-stratified effect modification as an underpowered screen")
rep("None of the 108 module \u00d7 driver interactions survived FDR, and we interpret this as no statistically supported heterogeneity was detected, although interaction analyses were underpowered, rather than as proof of stability across driver backgrounds.",
    "None of the 108 module \u00d7 driver interactions survived FDR; we interpret this as no statistically supported effect modification was detected, although the screen was underpowered, rather than as proof of stability across driver backgrounds.")
# 22 Discussion 4.8 limitations upgrades
rep("Composition: xCell is a single deconvolution; a full 27-cohort EPIC pass showed only moderate concordance with xCell for endothelial (\u03c1=0.56) and immune (\u03c1=0.44) fractions and weaker agreement for fibroblast/CAF (\u03c1=0.28) and epithelial/cancer (\u03c1=0.09) fractions, and residualization can over-correct.",
    "Composition: xCell outputs are enrichment scores rather than measured proportions; a full 27-cohort EPIC pass agreed only moderately with xCell (endothelial \u03c1=0.56, immune 0.44, fibroblast/CAF 0.28, epithelial/cancer 0.09). Primary composition inference used joint models (module ~ disease + composition [+ patient]); two-step residualization, which can over- or under-correct, was retained as a sensitivity and classified a larger, only partially overlapping set of states.")
rep("Meta-analysis: DerSimonian-Laird with SMD-variance approximations (paired correlation 0.5); the conservative REML/Hartung-Knapp re-estimate retained only 4 pooled-significant states, so meta-analysis is reported as an underpowered sensitivity layer. Small k in several meta cells makes I\u00b2 unstable.",
    "Meta-analysis: effect sizes were standardized on a common two-group scale, with matched cohorts converted using empirically estimated within-pair correlation (fixed r = 0.5/0.7 sensitivity returned identical pooled-significant sets); small k in several meta cells makes I\u00b2 unstable. Under the conservative REML/Hartung-Knapp inference 11 of 170 states were pooled-significant, so meta-analysis is reported as a confirmatory but under-powered layer.")
rep("External OS validation was context dependent: CRC (GSE39582) and PAAD (GSE21501) TCGA module-OS signals were not reproduced, whereas three of five STAD signals (ACRG) were replicated.",
    "External OS validation was context dependent and signal-specific: in CRC (GSE39582; n=573, 190 events), VEGF/PDGF was replicated whereas the ERBB-ligand protective signal was not; in PAAD (GSE21501), none of the seven TCGA-adverse module signals was reproduced; in gastric cancer (ACRG/GSE62254), three of five vascular/stromal signals were replicated. Stage adjustment was not possible in GSE39582 (stage annotation not usable in the public record) and is a residual caveat for the CRC result.")
rep("A marker-based tumour-purity adjustment (TCGA-PAAD) did not materially attenuate the module-OS signals.",
    "A marker-based tumour-purity proxy (TCGA-PAAD) did not materially attenuate the module-OS signals; the proxy is expression-derived and is not a substitute for measured purity.")
# 23 Conclusion
rep("Across 27 public transcriptomic cohorts, growth-factor module expression was strongly context dependent. Many lesion-control differences attenuated after expression-derived composition adjustment, whereas a smaller subset remained detectable and could be localized to specific cellular compartments in independent single-cell datasets. These results provide composition-aware hypotheses rather than direct evidence of pathway activation or therapeutic actionability, and they argue that composition- and replication-aware reporting should become standard for tissue-level pathway atlases.",
    "Across 27 public transcriptomic cohorts, growth-factor module expression was strongly context dependent. Many lesion-control differences attenuated after joint composition adjustment, and only six states remained composition-robust (CRC WNT/\u03b2-catenin, EPH, FGFR loss, IGF/INSR loss and VEGF/PDGF upregulation; IBD JAK-STAT), a subset of which localized to specific cellular compartments in independent single-cell datasets. These results provide composition-aware hypotheses rather than direct evidence of pathway activation or therapeutic actionability, and they argue that composition- and replication-aware reporting should become standard for tissue-level pathway atlases.")
# 24 Table S9 line after S8
rep("**Supplementary Table S8.** Leave-one-gene-out module robustness (per-gene Spearman r and module-level summary).",
    "**Supplementary Table S8.** Leave-one-gene-out module robustness (per-gene Spearman r and module-level summary).\n\n**Supplementary Table S9.** Per-state evidence matrix (per-cohort robustness; unified-scale meta-analysis; joint composition models; single-cell localization; TCGA and external prognosis).")
# 25 Methods 2.6 per-cancer FDR family clarification
rep("The OS layer scored 17 module features plus a single-gene EGFR feature (18 features per context; 108 tests) by univariable Cox (HR per 1 SD; n \u2265 40; \u2265 10 events; BH-FDR within context); the single-gene EGFR feature was retained in the univariable layer only.",
    "The OS layer scored 17 module features plus a single-gene EGFR feature (18 features per context; 108 univariable tests across six contexts). BH-FDR was applied within each context-specific family of 18 tests, so the 17/108 FDR<0.05 count is not a single genome-wide claim; the single-gene EGFR feature was analysed in the univariable layer only, and multivariable sensitivity re-fit the 15 module features with covariate data.")
# 26 table footnote/others 'xCell-robust' claims in abstract? abstract fixed. Heatmap legends mention xCell stays fine.
# 27 4.5 external discussion mention joint support for CRC VEGF
rep("We therefore treat the CRC ERBB-ligand protective direction as a TCGA-specific, hypothesis-generating observation and list plausible causes (differentiation state, residual normal-epithelial content, treatment mix, assay differences); the STAD vascular/stromal axis is the positive control for externally reproducible module-OS signals.",
    "We therefore treat the CRC ERBB-ligand protective direction as a TCGA-specific, hypothesis-generating observation and list plausible causes (differentiation state, residual normal-epithelial content, treatment mix, assay differences); the STAD vascular/stromal axis and the CRC VEGF/PDGF signal (which also survived joint composition adjustment) are the externally supported OS signals.")
ok=miss=0
for a,b in R:
    if a in s: s=s.replace(a,b,1); ok+=1
    else: miss+=1; print("MISS:", a[:80].replace("\n"," "))
open(dst,"w",encoding="utf-8").write(s)
print(f"applied {ok}/{len(R)} misses {miss}")
import re
m=re.search(r"## Abstract(.*?)## 1\.", s, re.S)
print("abstract words:", len(re.findall(r"\S+", m.group(1))) if m else "NA")
